### PR TITLE
Module 10 - distributed system 1

### PR DESCRIPTION
**Pull request by jon-bell**
Not a big lift here - just tidied up a little bit. I saw Mitch's comments about the cheesy animations but I like them :) I am putting more time into module 11 - the "REST" lesson will now include web sockets, and will compare/contrast using push vs pull pattern, and include a pointer back to typed emitter pattern for web sockets.

### CODE REVIEW

**Comment by mwand** [comment]
Sounds great!  Do you have any thoughts about relating the REST material to the rest of  module 11?

**Comment by jon-bell** [comment]
> Sounds great! Do you have any thoughts about relating the REST material to the rest of module 11?

Yes - it becomes an "implementation-level technologies" lesson (and some of the principles, like "stateless" make more sense when you see the alternative of a very stateful web socket)

**Comment by mwand** [comment]
Remember also that I covered emitters in Module 05, so you can take advantage of that.

**Comment by abhutta0** [comment]
lgtm

**Pull request merged**
