### PR TITLE
module17-ethics

### PR DESCRIPTION
**Pull request by iamabhutta**
starting with fa23 version

### CODE REVIEW

**Comment by abhutta0** [comment]
Added a couple of slides with some new example and a new slide at the end ...

**Comment by mwand** [comment]
I have several proposed changes to the slides; I will do that in a new branch

**Comment by mwand** [comment]
Updated the slides:  
* Changed a few titles
* Added example about Adobe Firefly images (and added link to lecture page)
* Hid a few slides
   * s15 Equity and Software
   * s16 Reducing Inequities
   * s33 A Lot more needs to be done (most content redistributed)
   * Feel free to unhide these if you like them.

Otherwise lgtm.  Feel free to merge.

**Comment by abhutta0** [comment]
lgtm. Will wait for @jon-bell to comment and then will merge. Thanks

**Pull request merged**
