### PR TITLE
module14-cicd

### PR DESCRIPTION
**Pull request by abhutta0**
starting with fa23 files

### CODE REVIEW

**Comment by mwand** [comment]
Jon, you should go back and look at the slides from Spring 23 (and possibly earlier).  I know I did the Fall 23 slides, and I'm not sure I improved them-- for example, I cut way down on the Knight Capital story, which may have been a mistake.

Also, the slides, on a quick skim, seem to cover several disconnected topics: 
* continuous integration (with numerous obscure slides that I don't understand)
* code review  (why is this here?  we've talked about code review in earlier modules)
* continuous(?) deployment/continuous delivery (are these the same thing? a lot of "look at what these big boys do" -- do we really care about the details of FB's branch control?
* monitoring
* A/B testing (or FB's AB-to-the-max testing).
* Safeguards in deployment (Knight capital, maybe we should use the S24 autograder.io rollout :-) )
The disconnect between these topics is manifest in the 3 LOs, which seem not to have any connection to one another.

Maybe I'll go through and do a slide-by-slide discussion, but I think it might be better to wait until you (Jon) think harder about what should be in this module.  Or maybe you may decide to punt, and redesign it for next semester.

**Comment by jon-bell** [comment]
I'll definitely be able to cut through at least some of this today, but if @abhutta0 is wiling/able to swap his Sec 3/5 lectures (so this Thurs/Fri is discuss project revisions and next Tues is continuous development), I will be able to have a reasonable draft for discussion this Weds, and then have time to iterate through it again.

**Comment by abhutta0** [comment]
done. Added another project work session for tomorrow (Tuesday) and moved s3+s5 lectures to Wed/Thur.

**Comment by jon-bell** [comment]
Great, thanks! I will be working on this (and the CI/CD activity) later today and tomorrow, then.

**Comment by jon-bell** [comment]
I think that this could still benefit from more review and iteration, but I also think that this hopefully constitutes a significant improvement on past attempts to cover these topics. I've added another example at the start, removed code review, added more details on practices of CI (including a brief sidebar on dependency management and versioning), more on practices of CD and monitoring, and a comparison between continuous delivery and TDD as software quality approaches. Learning objectives are, I think, much better now too.

**Comment by mwand** [comment]
reviewing [801b8e3]

Overall, I like this deck a lot. As a general comment, the speakers notes need to be edited to reflect where they are in the new deck.   Also, I have a few suggestions for reordering some of the slides.

Hope this is helpful.  --Mitch

s5: what in this lecture is this slide connected to?  

s10:  s5 might better go here, where its application is clear.

s13: notes talk about "that same project's CI pipeline"  what project is that?

s14: the slide raises good questions, but the answers are hidden in the speakers notes.  Maybe move them into a slide?

s14: speakers notes say "We'll look at a few examples"  rly?

s15: the visuals are inscrutable.  All the content is in the yellow boxes.  + say "and you can write scripts to automate all this."  No need to display the scripts, since we don't expect students to write them.

s16: "fuzzers like this one"?  We don't care what is being benchmarked, or even how you write the scripts to do the benchmark-- the point is that you have a centralized repository, so you can generate graphs like this one.   Here is the data comparing the performance of two versions of the SUT; here higher is better.  

s17: move earlier, say right after s14?

s18: may want to stay right after s17.  Notes say "more on next slide".   Also, visuals are ineffective.

s15-16 are independent of _when_ the CI runs; s17-18 are exactly about _when_ to run the CI.
s20: should probably immediately follow s18: "Attributes of effective CI processes".  New title of s20: "Effective CI processes allocate enough resources to avoid flaky tests.".   The graph is inscrutable, maybe delete it.

I think a better order for this group of slides is:

s13 (title as is)
s15
s16
s14: How do we apply ...
s18: Attributes of Effective CI Processes
s17: Effective CI processes are run often enough to reduce debugging effort
s20: Effective CI processes allocate enough resources to avoid flaky tests

then on to s21 et seq.

s32-33:  visual doesn't add anything

s33: Is a "recipe" different from a "script" like the one on s12?
s31: seems out of place-- 

s35: Wow!  Spinnaker looks cool.  Might be better directly following s33.  s31 could then follow this one (two examples of complicated things you could build) 

s44-46: I still think this is too far down in the weeds.

s47: I like this one.   

Is FB's approach to CD related to the mantra of "move fast and break things"?

**Comment by jon-bell** [comment]
> s5: what in this lecture is this slide connected to?

Automating feedback loops is the core premise to CI/CD. I moved this to after slide 10, maybe a bit clearer there, and changed the subtitle

> s10: s5 might better go here, where its application is clear.

Moved.

> s13: notes talk about "that same project's CI pipeline" what project is that?

Whoops, there had been more on presto that I deleted. Replaced the screenshot with the autograder pipeline.

> s14: the slide raises good questions, but the answers are hidden in the speakers notes. Maybe move them into a slide?
> s14: speakers notes say "We'll look at a few examples" rly?

I touched up the slide so that there is more leading to the tradeoff/answers than there had been. The examples were bad and were cut. Will think about new examples next time, maybe.

> s15: the visuals are inscrutable. All the content is in the yellow boxes. + say "and you can write scripts to automate all this." No need to display the scripts, since we don't expect students to write them.
> s16: "fuzzers like this one"? We don't care what is being benchmarked, or even how you write the scripts to do the benchmark-- the point is that you have a centralized repository, so you can generate graphs like this one. Here is the data comparing the performance of two versions of the SUT; here higher is better.
> s17: move earlier, say right after s14?
> s18: may want to stay right after s17. Notes say "more on next slide". Also, visuals are ineffective.
> s15-16 are independent of when the CI runs; s17-18 are exactly about when to run the CI.
> s20: should probably immediately follow s18: "Attributes of effective CI processes". New title of s20: "Effective CI processes allocate enough resources to avoid flaky tests.". The graph is inscrutable, maybe delete it.
> I think a better order for this group of slides is:
> s13 (title as is)
> s15
> s16
> s14: How do we apply ...
> s18: Attributes of Effective CI Processes
> s17: Effective CI processes are run often enough to reduce debugging effort
> s20: Effective CI processes allocate enough resources to avoid flaky tests
> then on to s21 et seq.

Yes, this works better - updated.

> s32-33: visual doesn't add anything

I would plan to talk to the visual briefly to explain what a common web app architecture looks like. The slides came from another deck that I wrote on IaC that walk through how to provision such an app manually, and then using IaC. I'd rather leave the figure as-is for now.

> s33: Is a "recipe" different from a "script" like the one on s12?

Yes. I added the bullet "Engineers define “healthy” states for infrastructure, then system automatically provisions, validates, and (if needed) repairs deployed resources" - it is somewhat different from a regular old script in that it effectively has assertions (that say what "correct" infrastructure should look like), and each step in the script has some logic to recover from a failed deployment

> s31: seems out of place--

I moved the figure onto slide 30

> s35: Wow! Spinnaker looks cool. Might be better directly following s33. s31 could then follow this one (two examples of complicated things you could build)

Yeah, that makes sense (assuming you meant directly following s30 "CD relies on staging environments")

> s44-46: I still think this is too far down in the weeds.

I think that, because it is so old, it is actually a reasonable example of what many smaller companies may be doing today (e.g. if you are still below the facebook-scale). I am leaning towards leaving it in there for now, and see how it goes - if the material is running long I think that there's not much lost by cutting it, but I also think that it is interesting to see a detailed discussion of how this kind of process is implemented.

> s47: I like this one.
> Is FB's approach to CD related to the mantra of "move fast and break things"?

Thanks! Yes, it's very much "move fast and break things," with a bit of "grow or die" and also "you are rewarded for new features, not for scaling old ones"

**Comment by abhutta0** [comment]
I have tried fixing fonts on new slides (and heading size on all). I may have missed one. On your last pass, please check s34.
Also please check notes of s33. Quick pass on notes could help
rest lgtm

**Comment by mwand** [comment]
Thanks for doing all that editing.   A few straggling bits:

s11: put directly after s9.  (swapping s9 and s10)

swap s17 and s18

maybe swap s23 and s24  (or maybe move s23 to after s25?)

move s32 to right after s29 ?

s33 is out of place;  it uses the term IaC before it's defined.

Maybe resequence: s29, s32, s35, s34, s30, s33  (or maybe s33, s30), s36

s37 needs to go later: maybe after s43 (as a warning not to over-rely on the tools we just talked about).
I will probably skim over these slides.

s44-46:  I understand this better after your comments.  

s45: deletable.  Also: who are the "people" whose experience is supposed to be made better?

Basic idea:  instead of deploying from master to subsidiary branch, deploy directly from master, but to a small set of (perhaps unwitting) beta-testers; monitor the results to see if the deployees should be expanded (C1-C2-C3).

**Comment by jon-bell** [comment]
> s11: put directly after s9. (swapping s9 and s10)
> swap s17 and s18
> maybe swap s23 and s24 (or maybe move s23 to after s25?)

Great - done!

> move s32 to right after s29 ?
> s33 is out of place; it uses the term IaC before it's defined.
> Maybe resequence: s29, s32, s35, s34, s30, s33 (or maybe s33, s30), s36

I think that 30 is in the right spot now, but the lecture notes and bullets don't make clear why it fits. This slide should provide an introduction to the idea of having split deployments (deploy to different environments). Re-titled to "Split Deployments Mitigate Risk" and added some detailed notes.

I added more notes in each slide in this sequence that makes my intended narrative/transition clearer. I moved 32 to be before 31. 

I think that this is going to be the best that I've got for this time around. After giving our lectures this week, maybe we can refine the learning objectives a little more, and then that will help to sort out how the material should be structured/presented in the future.

> s37 needs to go later: maybe after s43 (as a warning not to over-rely on the tools we just talked about).

Moved

> s45: deletable. Also: who are the "people" whose experience is supposed to be made better?

Added presenter note:
> The “people” whose experiences were improved were:
> - Devs trying to get changes deployed (who wanted the most frictionless process)
> - Build cops and release engineers who were responsible for executing the QA and overall process.

> Basic idea: instead of deploying from master to subsidiary branch, deploy directly from master, but to a small set of (perhaps unwitting) beta-testers; monitor the results to see if the deployees should be expanded (C1-C2-C3).

Yup, that is it. It requires a lot more automation, but once you reach a certain scale it's worth paying the upfront cost to automate. Maybe interesting to still think about at smaller scale though, because these automations eventually become effectively utility infrastructure that become easier to use.

**Comment by jon-bell** [comment]
I'm not going to have any more time for iterating on this, so will merge/close this, but please feel free to reorder as you see fit, and ask for elaboration on presenter notes for any specific slide(s).

**Pull request merged**
