### PR TITLE
Module12 larger tests

### PR DESCRIPTION
**Pull request by jon-bell**
Slides are mostly where I would like them to be - I think that this does a pretty good job of reflecting the feedback in the sheet from last time, plus added some new content. I reworked the narrative getting to mocks and spies, and I hope that this time it is much more clear what the difference between a mock and a spy is.
- Added mock example for testing pushing clock
- Added spy example for testing pushing clock
- Clarified spying on an object vs spying on a module
- Refactored `await expect(somePromise).resolves.toEqual` to `expect(await somePromise).toEqual` - much less verbose and confusing mixing `resolves` with `await`

I may put together a short activity for testing the todo app, we will see how things go tomorrow.

### CODE REVIEW

**Comment by abhutta0** [comment]
LGTM
In the past we didn't have an activity for this lecture and I usually would ask students to look thru coveytown and find examples of mocks and spies and share with the class.

**Comment by jon-bell** [comment]
> I think ss7-8 should immediately follow s4. Once you establish the idea of testing with a custom observer, you can say "remember back in Module , when we talked about test doubles. That's what we did! We build a fake listener to replace the real listeners in our application".

Moved.

> s13, maybe add "OTOH: ...." to the title?

Updated title

> s14: are we testing the clock or the listener? Up to this point, we know we are testing the clock, because the listener is something we wrote (or, in the case of the mock, caused to be created) ourselves-- it's something we control.

You are testing the ProducerClock. Added more discussion in the presenter notes for this slide.

> s14: Should this point out that spyOn is global.? Imagine that instead of invoking clock1.tick (), the test invoked some other piece of code, which in turn invokes clock1, which in turn calls clock1.tick. That was the situation in the Fall 23 slide (M12.1 s24). I always found that really hard to understand, hence my comment "mocks are local; spies are global".

"Mocks are local; spies are global" is also a somewhat muddy explanation, unfortunately. Spies are local to whatever they spy on. In this case, the spy is "local" to clock1. Anyone else who has a reference to clock1 will also see the spy. The same argument applies to listener1 on slide 12. I added a new slide 15 that I think explains this much more clearly.

> I think the point is that spies are useful when we control neither the SUT or the system in which the SUT is embedded. Do I understand this correctly?

Yes, exactly. I put these words on the new slide 15.

> s18: "The best way to reduce this coupling to build the mocks around the interface you control" What does this mean? Tell us more.

> I think the problem is back on slide 15: exactly what property of echo are we trying to test? (I confess that this code, and hence this problem, is mine :-) I think this might be an integration test, not a unit test.

Whoops, I finished the sentence. We are before discussing unit vs integration tests. You are right that to unit test echo, you would need to mock axios. There's not really a better way around it. But, for testing clients that *call* echo, mocking echo is a better choice.

> s21: I can see how the kind of jest test that we wrote might work for this-- you can run the same jest test that you did before, only in a different setup. But how do you even write the bigger tests, like the one on s26? Maybe a forward reference to the CI workflows we do later? Maybe forward reference to capture/replay, as on slide 30?

I added to the presenter notes on these slides. I didn't want to put more on the slides because "how to implement" these tests is not a learning objective for the module, and seemed like a sidebar/distraction.

> You wrote:
> 
> Refactored await expect(somePromise).resolves.toEqual to expect(await somePromise).toEqual - much less verbose and confusing mixing resolves with await
> I like this! Where is it? [BTW, I should update the async lecture to incorporate this]

Slides 17, 18, 19, (numbers correspond to the latest version of the slide deck, not what you reviewed)

> Also, on the discord you wrote about including an example from covey.town that shows checking for multiple effects.
> 
> What happened to that?

I looked through quite a few of the tests in Covey.Town, and unfortunately I do not think that they would be good examples here. The entire test suite is derived from the autograders - these tests are not really representative of the tests that one might write if they were simply trying to create a good test suite. For example: we check for the absence of side effects. We also have way more "unit" tests (checking a single method) as opposed to "small integration" tests (checking a few methods) because we need to assign points at that level of granularity. These unit tests make use of some pretty gross mocks that I would are anti-patterns: in some cases, there is more implementation to support the mocks than there is for the production code. This is an interesting side discussion, but the tldr is that in the future, maybe we should set up time specifically for creating those new tests to use as examples.

> Looking forward to the next draft.

Thanks for all of the great suggestions and feedback! However, just to manage expectations: it is unlikely that I will have bandwidth for another round of revisions this semester (but will save the notes for next term).

**Comment by mwand** [comment]
s1: update copyright date.

> "Mocks are local; spies are global" is also a somewhat muddy explanation, unfortunately. Spies are local to whatever they spy on. In this case, the spy is "local" to clock1. Anyone else who has a reference to clock1 will also see the spy. The same argument applies to listener1 on slide 12. I added a new slide 15 that I think explains this much more clearly.

I like the new s15.

I think the point is that spies are useful when we control neither the SUT or the system in which the SUT is embedded. Do I understand this correctly?

> Yes, exactly. I put these words on the new slide 15.

We have to have _some_ control over the system in which the SUT is embedded, because we have to be able to name the place where the spy is to be applied.   And the comment on the third code line is misleading: it should be "Spy on calls to notify on this *client*".    And we need to say somewhere that the clockClient in the second line is just some arbitrary listener that we happen to know the name of.

>> s18: "The best way to reduce this coupling to build the mocks around the interface you control" What does this mean? Tell us more.

> Whoops, I finished the sentence. We are before discussing unit vs integration tests. You are right that to unit test echo, you would need to mock axios. There's not really a better way around it. But, for testing clients that call echo, mocking echo is a better choice.

Got it.

>> s21: I can see how the kind of jest test that we wrote might work for this-- you can run the same jest test that you did before, only in a different setup. But how do you even write the bigger tests, like the one on s26? Maybe a forward reference to the CI workflows we do later? Maybe forward reference to capture/replay, as on slide 30?

> I added to the presenter notes on these slides. I didn't want to put more on the slides because "how to implement" these tests is not a learning objective for the module, and seemed like a sidebar/distraction.

Got it.

You wrote:

>> Refactored await expect(somePromise).resolves.toEqual to expect(await somePromise).toEqual - much less verbose and confusing mixing resolves with await
I like this! Where is it? [BTW, I should update the async lecture to incorporate this]

> Slides 17, 18, 19, (numbers correspond to the latest version of the slide deck, not what you reviewed)

Got it.  It would be useful to point out that this is different from what we wrote in the async lecture.

> Thanks for all of the great suggestions and feedback! However, just to manage expectations: it is unlikely that I will have bandwidth for another round of revisions this semester (but will save the notes for next term).

If you would like, I can make the tweaks I proposed (s1, s15, s17notes, s19notes).  I can make it a separate branch, or just do it in module12-larger-tests.  Let me know.

**Comment by jon-bell** [comment]
Feel free to make changes directly and push. I may be able to skim quickly tomorrow morning, but otherwise am on other work items between now and my lecture on Thursday. On Feb 13, 2024, at 2:45 PM, Mitchell Wand ***@***.***> wrote:﻿
s1: update copyright date.

"Mocks are local; spies are global" is also a somewhat muddy explanation, unfortunately. Spies are local to whatever they spy on. In this case, the spy is "local" to clock1. Anyone else who has a reference to clock1 will also see the spy. The same argument applies to listener1 on slide 12. I added a new slide 15 that I think explains this much more clearly.

I like the new s15.
I think the point is that spies are useful when we control neither the SUT or the system in which the SUT is embedded. Do I understand this correctly?

Yes, exactly. I put these words on the new slide 15.

We have to have some control over the system in which the SUT is embedded, because we have to be able to name the place where the spy is to be applied.   And the comment on the third code line is misleading: it should be "Spy on calls to notify on this client".    And we need to say somewhere that the clockClient in the second line is just some arbitrary listener that we happen to know the name of.


s18: "The best way to reduce this coupling to build the mocks around the interface you control" What does this mean? Tell us more.



Whoops, I finished the sentence. We are before discussing unit vs integration tests. You are right that to unit test echo, you would need to mock axios. There's not really a better way around it. But, for testing clients that call echo, mocking echo is a better choice.

Got it.


s21: I can see how the kind of jest test that we wrote might work for this-- you can run the same jest test that you did before, only in a different setup. But how do you even write the bigger tests, like the one on s26? Maybe a forward reference to the CI workflows we do later? Maybe forward reference to capture/replay, as on slide 30?



I added to the presenter notes on these slides. I didn't want to put more on the slides because "how to implement" these tests is not a learning objective for the module, and seemed like a sidebar/distraction.

Got it.
You wrote:


Refactored await expect(somePromise).resolves.toEqual to expect(await somePromise).toEqual - much less verbose and confusing mixing resolves with await
I like this! Where is it? [BTW, I should update the async lecture to incorporate this]



Slides 17, 18, 19, (numbers correspond to the latest version of the slide deck, not what you reviewed)

Got it.  It would be useful to point out that this is different from what we wrote in the async lecture.

Thanks for all of the great suggestions and feedback! However, just to manage expectations: it is unlikely that I will have bandwidth for another round of revisions this semester (but will save the notes for next term).

If you would like, I can make the tweaks I proposed (s1, s15, s17notes, s19notes).  I can make it a separate branch, or just do it in module12-larger-tests.  Let me know.

**Comment by mwand** [comment]
added bullet per Adeel's comment above

**Comment by mwand** [comment]
merging.   I may do some more rewriting later tonite, but I'd rather have this all nicely in main.

**Pull request merged**
