### PR TITLE
react tutorial

### PR DESCRIPTION
**Pull request by abhutta0**
starting from fa23 version.

### CODE REVIEW

**Comment by kevintyj** [comment]
Added (Modified):
- Explains the move from React class components to functional components
- Explain onCleanup behavior using the useEffectHook
- New table for possible summary of uses of useEffect
- A little reference to react's amazing docs on JSX on the JSX parser
- Fixes all codeblocks from ts to tsx (does not effect anything)

**Review by kevintyj — APPROVED** [review]
LGTM 🙌

**Comment by mwand** [comment]
Needs to say that next.js renders whatever is in app/pages.tsx  ; whatever is in that file becomes the root component.

Other than that, it is very good!  It will save me a lot of time in lecture. Thank you to all who contributed!

**Comment by hkrish28** [comment]
I have reviewed the PR and added some slight changes:
- Fixed a few typos in the document and refactored some trivial code block errors.
- Updated a broken link to the next.js documentation
- Rephrasing some comments to add clarity.
- Noticed the code block in the Props subsection was not getting detected (even though ```tsx was provided) and that cascaded into text and put some text into code blocks until the next section. Fixed it by adding a new line before the code block.

**Review by hkrish28 — APPROVED** [review]

**Pull request merged**
