### PR TITLE
Update submission and grading section

### PR DESCRIPTION
**Pull request by james-perretta**
A couple of questions:

1. @abhutta0 Did you mean 1/7 instead of 12/7 for the date that the autograder roster was updated?
2. @jon-bell What hint limits do you think we should use? I suggest one of the following (in no particular order):
    1. 2 hints per section per submission 
    2. 4 hints per day
    3. One of the previous options but with different numbers?

### CODE REVIEW

**Comment by abhutta0** [comment]
yes 1/7

**Comment by jon-bell** [comment]
> @jon-bell What hint limits do you think we should use? I suggest one of the following (in no particular order):
2 hints per section per submission
4 hints per day

That sounds fine.

> Option https://github.com/neu-se/CS4530-Spring-2024/pull/1 or https://github.com/neu-se/CS4530-Spring-2024/pull/2, but with different numbers?

Sorry - I am not sure what this means?

**Comment by james-perretta** [comment]
@jon-bell Sorry, I did a bad job with the markdown. Another way to phrase it would be to choose from these options:

1. 1 hint per section per submission
2. 2 hints per section per submission
3. 3 hints per section per submission
4. 2 hint per section per day
5. 3 hints per section per day
6. 4 hints per section per day

It's also possible to impose a per submission and a daily limit, although the daily submission limit already imposes a certain daily limit. I'm maybe leaning towards a per submission limit of 1 or 2 hints if there are 2ish hints per mutant (I think we should aim for at least 2 hints per mutant). Thoughts?

**Comment by abhutta0** [comment]
Not sure what the context is for these limits (i.e., per section). I would like to avoid a situation where students in different sections see different hints for the same problem (or failing test). As long as we have same limits for all sections, we should be ok (if that means that students will be seeing one or two hints every day and next day they might see few more and so on) ... 
Now if section means something else (like section of the code or whatever), then no worries.

**Comment by jon-bell** [comment]
oh, ok. I assume that per-section you mean per-section of the assignment specification. if that's the case, doing 2 hints per-section sounds like a good starting place.

**Comment by james-perretta** [comment]
@abhutta0 By "section" I mean the test grading sections, e.g., "test join", "test leave", etc. Is there another term that would be clearer?

**Comment by jon-bell** [comment]
"Per-task" sounds good to me. Can you finalize this language? I think that we are all set otherwise to release this.

**Pull request merged**
