### PR TITLE
Module 11

### PR DESCRIPTION
**Pull request by jon-bell**
Most of the new material is in 11.3 (web sockets), and in 11.1 (discussion of tradeoffs between architectures). Trimmed the architecture discussion down a bit otherwise. When I deliver modules 10+11 in a single lesson, I plan to skip most of 10.2 (no CAP theorem stuff), some of the tsoa details, and the activity.

### CODE REVIEW

**Comment by mwand** [comment]
I like the presentation of websockets.  The sequence diagrams are very useful. several comments:

The name of this branch doesn't follow the convention of other branches in the repo, which is moduleNN-topic .  (Same for module 10)

Need Learning Objectives for this module.  Maybe do this separately for Modules 10-11, and for Lesson 11.3?

s4: text is awfully small (minor).   The key point is in the script: "Clients open a web socket connection with a server, and then the server can emit (push) events to clients. Similarly, the clients can push to the server".  But this information is buried in the diagram.  It would be helpful to make these into text bullets on the slide.  You could create a slide with these bullets that would precede this one.

[Also: when the server emits a message, is it to an individual client? Could say that there are ways to emit to a group of clients, or you could not address this issue.]

s5: "no clear request/response"  slide text is unclear unless you already know what is meant
What does "state explosion" refer to?
(I'd need some speakers notes here)

s6: where are io, socket defined?   This avoids the essential issue of how the client and server reach an agreement prior to any connection.  (I eventually found the key lines, which I'll send you in a separate message.  Also it would help to say how this is done in covey.town.) 

s8: first box has bad line wrap.   What does this example add past the code on s6?  I think it does, but it would be helpful if the script explained the justification.

s10: This is very good. "Most modern applications use one or both of these protocols".  This might be a place to repeat s3, perhaps with examples from covey.town to illustrate the choice.

s11 (if there were multiple [insert: servers])

s12: Should we clarify for the benefit of those students who don't know that there are 4 kinds of http requests?

s17: Students ask every time:  how do I choose which of these parameter-passing methods to use?  What are the advantages/disadvantages of each?

Hope this is helpful.

**Comment by mwand** [comment]
Here's how I set up my toy example, which shows how client and server agree on a url and port, and how they initialize the connection.  I've included a complete zip file, and an outline.txt with just the key parts.  Feel free to tweak these to match your setup.

[typed-sockets.zip](https://github.com/neu-se/CS4530-Spring-2024/files/14215430/typed-sockets.zip)

[outline.txt](https://github.com/neu-se/CS4530-Spring-2024/files/14215428/outline.txt)

**Comment by jon-bell** [comment]
Thanks for the feedback! I've just pushed updates to 11.3, some notes below:

> The name of this branch doesn't follow the convention of other branches in the repo, which is moduleNN-topic . (Same for module 10)

 OK, will use that convention next time. Maybe it goes in the README :)

>Need Learning Objectives for this module. Maybe do this separately for Modules 10-11, and for Lesson 11.3?

I'm not sure what you mean - we have L.O's on each lesson, and on both modules. 

>s4: text is awfully small (minor). The key point is in the script: "Clients open a web socket connection with a server, and then the server can emit (push) events to clients. Similarly, the clients can push to the server". But this information is buried in the diagram. It would be helpful to make these into text bullets on the slide. You could create a slide with these bullets that would precede this one.

Redrawn. I think that the yellow callouts are sufficient, and hopefully being at 32px instead of 12px makes it clearer.

> [Also: when the server emits a message, is it to an individual client? Could say that there are ways to emit to a group of clients, or you could not address this issue.]

Added a bullet on slide 5

> s5: "no clear request/response" slide text is unclear unless you already know what is meant  
What does "state explosion" refer to?  
(I'd need some speakers notes here)

Added speaker notes for this slide

> s6: where are io, socket defined? This avoids the essential issue of how the client and server reach an agreement prior to any connection. (I eventually found the key lines, which I'll send you in a separate message. Also it would help to say how this is done in covey.town.)

I added a note and a pointer to the documentation. I am doing all of modules 10 and 11 in a single day, and am not very excited to add more content or examples, but please feel free to call this out when you go through your code snippet

> s8: first box has bad line wrap. What does this example add past the code on s6? I think it does, but it would be helpful if the script explained the justification.

Fixed, and added a script

>s10: This is very good. "Most modern applications use one or both of these protocols". This might be a place to repeat s3, perhaps with examples from covey.town to illustrate the choice.

Great! Again, trying to avoid adding more material right now.

>s11 (if there were multiple [insert: servers])

Uhh I am not sure why it said "if there were multiple..." or what you are suggesting.  I deleted the parenthetical. But, this is a good place to call out a difference from WebSockets, which I added to the notes

>s12: Should we clarify for the benefit of those students who don't know that there are 4 kinds of http requests?

I think that there are more than 4 kinds. The relevant ones are listed on slide 18

>s17: Students ask every time: how do I choose which of these parameter-passing methods to use? What are the advantages/disadvantages of each?

I added some guidelines here

**Comment by abhutta0** [comment]
love the additions in 11.3. After we add the concluding slide (learning goal), it should be set!

**Comment by mwand** [comment]
Seems fine so far as it goes.  I see your goal was to skinny it down, but
I'm sorry to see pipeline architectures go.  (I see that the F23 version
lists "event-driven architectures" on its list of architectures, but there
weren't any content slides about it. :-).

I may add those slides back for my presentation.

I very much like your slide 5 (Questions to Ask About Distributed
Architectures)  (delete ? at end of title, maybe).  In the long run, it
would be nice to put some answers (or partial answers) to these questions
for each of the architectures we consider).

I didn't see much else that was different.  Let me know if I missed
something important.

**Pull request merged**
