### PR TITLE
tutorial for typescript

### PR DESCRIPTION
**Pull request by abhutta0**
starting with fa23 version

### CODE REVIEW

**Comment by mwand** [comment]
don't see a need for detailed review.   lgtm.

**Comment by rumjhumsingru** [comment]
(Optional) Should we write information on what the **tsconfig.json** file is since we have it in all IPs ?

**Comment by rumjhumsingru** [comment]
(Optional) Should we write information on what the **tsconfig.json** file is since we have it in all IPs ?

**Comment by abhutta0** [comment]
> (Optional) Should we write information on what the **tsconfig.json** file is since we have it in all IPs ? The rest seems good to me!

A brief intro wont hurt.... You can update the tutorial @rumjhumsingru

**Comment by abhutta0** [comment]
Please update and confirm when done.

**Comment by mwand** [comment]
The purpose of the example is to do the Hello, World in the simplest
possible way.   For that, you don't need a tsconfig.json file at all, so
there's no point in even mentioning it.  The default configuration, without
any configuration files, works just fine.

OTOH, you might want to add a paragraph saying that real npm packages have
lots of configuration files, and every activity or IP that we publish will
come with a full set of configuration files, which you shouldn't mess with.

**Comment by rumjhumsingru** [comment]
I don't seem to have to write access to the repo and need to create to a new branch in a fork and then raise a PR to merge the changes. Can someone with write access please make the changes? Or should I raise the PR to merge the code into tutorial_ts?

**Comment by sushruth-06** [comment]
Noticed a small typo in the syntax of filter array function. It should be changed to `array.filter(callback[, object])` and currently it is `array.map(callback[,object])`. Rest of it looks good to me.

**Comment by rumjhumsingru** [comment]
I've added the tsconfig file info and the fixed typo in this commit.

**Pull request merged**
