### PR TITLE
Possible alternate M01 activity

### PR DESCRIPTION
**Pull request by mwand**
The old one is too broad; students really had no idea.  This one may be closer to home.

### CODE REVIEW

**Comment by abhutta0** [comment]
feel free to merge

**Comment by mwand** [comment]
I forgot to note that my solution is in the Activities folder (but not
linked).  It's open-ended, so of course many other things are possible.

**Comment by abhutta0** [comment]
I have added old one back (as scenario 1) and new one is scenario 2. You can rearrange them if needed and then merge.

**Comment by mwand** [comment]
Ahh, thanks.  I will merge to main.

**Pull request merged**
