### PR TITLE
module 09 - react part 2

### PR DESCRIPTION
**Pull request by abhutta0**
starting from fa23 version.
@mitch will update slides.

### CODE REVIEW

**Comment by mwand** [comment]
> Slide 14 talks about cleanup. The code on slide 15-16 doesn't really highlight the cleanup point.
> Notes say that we watch it on console.log ... not sure how. There isn't anything logged in slide 15/16.

Ahh, good point.  The cleanup function is the one on slide 9.  To watch it work, run the app on 15 with the browser console open (C-Shift-I).   I will have to think harder about creating a demonstration that doesn't require the console to be open.

>After slide 22, add an extra slide for transition .... say ... let's now switch to another topic: "how to do UI testing"?

Covered in the speaker's notes, but I probably should add a slide for people reading the pdf (or too lazy to read the speaker's notes)



After slide 22, add an extra slide for transition .... say ... let's now switch to another topic: "how to do UI testing"?

**Comment by abhutta0** [comment]
We should perhaps add a coding example for testing part. A short example would be nice as future addition.

**Comment by abhutta0** [comment]
important point to add in demo of slide 12/13: "your useEffect hook will also run twice in development mode, but not in production mode"

**Comment by mwand** [comment]
Yeah, when I get jest working with next.js I'll put a working example in
the package.

**Comment by abhutta0** [comment]
one MORE important piece of detail we are missing is: "the cleanup function you can (optionally) return from useEffect isn’t only called when the component is unmounted. It’s called every time before that effect runs again – to clean up from the last run." This can be demoed by adding console log statements in add/remove listeners of ArrayofClocks demo example.
Another detail we should add is use of "state updater" instead of concrete value (Spring23-Module8-Slide12) to avoid infinite loop.

**Comment by mwand** [comment]
Yes, you are right.
Thanks for pointing this out.
A lot of craziness here today; I will try to get these improvements in
place tomorrow.

**Pull request merged**
