### PR TITLE
module13 cloud

### PR DESCRIPTION
**Pull request by abhutta0**
initial files from fa23

### CODE REVIEW

**Comment by mwand** [comment]
My comments on the Fa23 slides are attached.  Hope they've arrived in time to be helpful.
[comments.txt](https://github.com/neu-se/CS4530-Spring-2024/files/14326562/comments.txt)

**Comment by jon-bell** [comment]
>slide 2: Learning Objectives:
>  need to be more specific
>  mention importance of multi-tenancy/resources-on-demand
 
Added
 
>  difference between virtual machines and containers
>    this seems like a random factoid; not sure if we've given the
>    students enough knowledge to do anything other than recite it.
>    Is it even so important?

I think that it's important, and added more content around this point, really focusing in on why it is important to avoid storing OS/dependencies multiple times

>  3rd bullet is lame (even though I think I wrote it)

I axed it

> s 3: speakers notes are very good.  Most of those bullets deserve to
be on the slide.

Added

> s3 may be out of place-- There's a nice sequence: s4,s5,s7,s8 s9 all
> make sense, even without the concept of the tall stack.
>
> I think s3 belongs near s20, where we use it to differentiate between
> IaaS and PaaS.  It may be that s4 belongs here too. The point is that
> we can talk about multi-tenancy and its implications without thinking
> about exactly what services are shared

Great idea - moved towards the end

> (What's the difference between s4 and s5?)

S4 shows the logical infrastructure that might be shared - you can talk about how each tier might have different requirements and be easier or harder to share among apps. Added some more presenter notes here.

> s 7: The levels in the stack picture don't line up with the bullets.  Maybe
> delete the stack picture.

Done

> s10: I don't understand the diagram.  What's the relationship between
> the idea of a "virtual machine" and the pictures on the right (after
> all, you could run virtual machines on your self-owned hardware-- we
> did this in CCS for many years, and maybe still do.)   What is the
> rightmost diagram supposed to show?  etc.

Reworked to clarify that the point is about abstraction responsibility (to the cloud, or potentially just to a different person, added bullets about on-prem VMs

> As near as I can tell, almost nothing prior to slide 20 actually
> depends on the tall-stack model.

Correct. The tiered diagram (with CDN, web servers, etc) is much more fitting - I added a modified version of that instead.

> s15: Is the difference between VMs and Containers really something our
> students have to know?  How does it contribute to our CLOs?

I've added some new slides (19, 20, 21). I think that it is important that students know the circumstances in which they should favor containers for deployment over VMs and why that is the case.

> s21 et seq: need to make names, etc., up to date.

These all still exist, and I added some new examples

> s22: Again, is this description up to date?  Are there other PaaS examples
that can provide a contrast?

Still up-to-date. Railway/Vercel/Render.com and friends all do the same thing. The contrast is on the prior slide (updated the text to make this clearer)

> s24: "Greater operating expenses" is not a "benefit to vendor-managed
> options" (or to anything else).

Uh, yeah. Changed to "Less capital investment, more flexibility in scaling" which might be a better point to make (because you don't put up the capital for the hardware, you don't need to worry about buying a bunch more quickly to scale up)

> Self-managed options do not "avoid vendor lock-in"-- what's a greater
> lock-in than a pile of hardware that you've bought?

I think that the point is really "Greater flexibility to migrate between software platforms" - once you are in a walled garden of a cloud system, it is difficult to migrate to another. I changed the bullet and added som enotes


> "More capital investment" is not a "benefit to self-managed options"
> or to anything else.

It's a benefit for a startup that is trying to show a high burn rate ;) I adjusted to "Potentially less operating expenses" along with some notes

> The tall-stack picture is irrelevant here-- the benefits described
> are independent of the levels being considered.

I think that I kept the tall stack here to highlight that you could choose gradients between these, even. I changed it to be just the 100% self-managed and the 100% SaaS, with a note that in reality you might end up carving out different layers in a cloud or self-managed situation.

> s 25: need to bring up to date.

Updated EC2 pricing, but a bit hard to get updated preferential pricing from Dell

> s 26: bring up to date.

I think that this is still overall OK.

I also re-arranged the SaaS discussion to add an example to it

**Comment by jon-bell** [comment]
Thanks @mwand for the additional feedback. I just pushed a revised version, and have some notes on your notes below. I also added "Pizza as a service" at slide 6, thanks to Michael Hilton for the suggestion!

> s4: Better title: What parts of this infrastructure can be shared
across different clients?

OK, changed to "What parts of this infrastructure can be shared across different clients?"

>>>s3 may be out of place-- There's a nice sequence: s4,s5,s7,s8 s9 all
make sense, even without the concept of the tall stack.

>>> I think s3 belongs near s20, where we use it to differentiate between
IaaS and PaaS. It may be that s4 belongs here too. The point is that
we can talk about multi-tenancy and its implications without thinking
about exactly what services are shared

>> Great idea - moved towards the end

> Is the current s5 the same as the old s3?

Yes.

> s6: speakers notes still talk about "diagram on the right"

Fixed this typo.

> s9: I still don't know what the diagram on the right is supposed to
> mean.

Added to the presenter notes: "The core benefit, as shown in the diagram on the right, is that you can abstract the management of every layer *below* “Virtualization”. An engineer who maintains VMs is entirely oblivious to the layers below it – they just see their VMs, and maybe are aware which VMs are on the same physical machine. That is: in addition to benefiting from co-tenancy (which could result in better utilization of the underlying hardware), you also benefit from a reduced maintenance burden – the physical servers, storage, network, and data center can be provided by others (be it a cloud provider, or something on-prem maintained by a different team or contractor)."

> What does "each VM in its own OS" supposed to mean?  Do you mean
> "different VMs on the same machine may run different OSs"?

Yes, sorry for typo, corrected to "Each VM runs its own OS"

> Your github comments indicate that you've reworked this slide, eg
> "added bullets about on-prem VMs".   But the new material is not on
> the pptx I pulled.

There is a new bullet under "Examples" on slide 9 that says "On-Premises: VMWare, Proxmox". The new note (quoted above, referencing the diagram) also discusses this point.

> s15: title is "Infrastructure as a service: containers".  Almost the
> same as the title on slide 9.   Which of these, if any, a "definition"
> of IaaS?   Might be clearer to make one or both of these into complete
> sentences that assert exactly what the slide is supposed to
> demonstrate.

I think that someone else wrote these titles :) I think that the definition for SaaS should live on slide 8, I changed the title to "Cloud services gives on-demand access to infrastructure, “as a service”" and bullets to:
* Vendor provides a service catalog of “X as a service” abstractions that provide infrastructure as a service
* API allows us to provision resources on-demand
* Transfers responsibility for managing the underlying infrastructure to a vendor

New s15 title: "A container contains your apps and all their dependencies" (same title as 16, same points)

> s17: another almost-identical title.   Also, what about this slide is
> specific to containers (vs VM-based IaaS)?

Nothing really specific to containers. To signal that this is just more XaaS, the new title is "XaaS: Containers as a Service"

> s18: again, making the title into a complete sentence would help a
> lot.

Re-title and added the bullet "An open standard for containers also exists (“OCI”)"

> s19-20: These belong earlier-- they are clearer than the presentation
> on s14-15.  Perhaps they should follow directly after s14.  I think the thesis
> is "containers are good because they are built in layers. Layers can
> be shared among the apps (or whatever) in a container.  Therefore
> containers can be smaller than corresponding VMs (or whatever)."
> The OS that was talked about on s14 et seq is just one example of a
> shareable layer.

Ah yes that's a great suggestion. I have moved them. That is definitely the thesis. I re-titled both slides to "Containers run layered images, reducing storage space"

> s18: The thesis is "Docker is good because it is a standardized
> container architecture, so it is available from many vendors".

Right. Re-titled as noted on above s18 comment

> s22: Worth pointing out that now we are finally getting back to the
> picture on ss3-4.  [This also suggests that ss5-21 were a digression
> about implementation strategies, but that's more radical surgery than
> we should undertake today.]

Yep, exactly. I am not sure that it will be clearer with this before VMs as a service, etc (because fundamentally, these PaaS are built using other IaaS - heroku literally just takes your app and runs it on EC2). I added some discussion of this to the presenter notes: "The next logical step is for the vendor to supply some or all of your middleware. That is, rather than thinking about ”x-as-a-service” where we think about generic infrastructure (e.g. VMs as a service, containers as a service), we can go back to our picture from the beginning, and ask – how can a vendor provide each of the *functional* components of our application, like the CDN, etc. as a service – so we don’t think or care about how it’s implemented (vms, containers, etc).
"

> s23: bullet #2 should say "Some PaaSs run your app in a container...";
> bullet #3 should says "Other PaaSs deploy your apps as single
> functions ..."; these two bullets should be aligned.  In fact, bullets
> 2-4 should all be aligned and inset under bullet #1.

Fixed.

> [This slide is very good, btw.  Now I know what AWS Lambda and friends
> are about.]

Great! I also added a presenter note: "One note about systems that provide functions-as-a-service (e.g. AWS Lambda): These systems are really handy when you have some code that you need to trigger to run infrequently, and runs quickly. They bill by the millisecond. So, they can become quite expensive quite quickly if they get called a lot (or if they are slow running). Recall when we discussed asynchrony, we examined the performance of making some web requests and found that each request might take 300-500 ms to complete. FaaS platforms will still bill you for that idle waiting time!"

> s24: title says that heroku runs containers, but the first bullet says
> "no container".   Need to clarify.  I think the title should be
> something like "Heroku is PaaS that takes just a web app, and runs it
> [in a container] on-demand".   (Is the fact that Heroku uses containers
> just an implementation detail?

Correct. I changed the bullet to "Provide an entry point to code, e.g. “npm start”, or optionally, a container specification" - you CAN provide a dockerfile, but as long as all that you need is a recent NodeJS environment, they spin up the container with their own spec.

> s27: why do you call this "private cloud" vs. plain old self-managed
> cluster?

I think that "self-managed cluster" does not carry any meaning to me in terms of the software used to manage it. However, "private cloud" suggests that you are running management services like public cloud providers offer. Otherwise, no difference.

> s27: private cloud costs don't include electricity, maybe other things
> needed to make apples-to-apples comparison

Absolutely - and this is included in the notes ("Self-managing a cluster like this requires a place to put them, power, and cooling - plus the administration of the software. (this dell cluster draws up to 90 amps of power, which is roughly half of the power that typically service as a house)."). The price of electricity to the operator is increasingly relevant. In our case, MGHPCC (the university cooperative datacenter where my server are) does not meter or bill tenants for power, and the technicians who do physical maintenance (e.g. if a RAM stick dies and I need someone to swap it out) are covered by general university overhead (no direct fees). 

> bullets could be clearer about the definition of constant workload vs
> variable workload

Added:
> * Variable workloads have different demands over time (most common)
> * Constant workloads require sustained resources (less common)

**Comment by jon-bell** [comment]
Right, sorry - I guess this was down to the wire :) I will merge.

**Pull request merged**
