### PR TITLE
module15-security

### PR DESCRIPTION
**Pull request by abhutta0**
starting from fa23. This lecture is needed on Wed 3/13

### CODE REVIEW

**Comment by jon-bell** [comment]
I compressed the number of slides on PKI/SSL, and added back two slides at the very end on secret managmeent as an example of security policy

**Comment by abhutta0** [comment]
Animation on slide 32 can also be reviewed to see if we can update. rest lgtm

**Comment by abhutta0** [comment]
Another issue is that pptx file now has new fonts that are not supported on Windows. If possible please replace those with those we already use in the slides (I suspect those are in new text we added in slides 38, 32, 29, 30.
image

**Comment by jon-bell** [comment]
* Updated titles on 29, 30
* Added "because your computer comes with a copy of the CA's public key, you can always check to see whether the SSL certificate you see hasn't been tampered with. " to the presenter notes on slide 31
* Ran "replace fonts" to try to remove instances of the fonts that Adeel specified

**Comment by mwand** [comment]
The version in the repo still gets the warning about "Avenir Next".  "Replace fonts" doesn't seem to do the job.  (I've hardly ever gotten "Replace Fonts" to work.)

These warnings (usually mostly for Helvetica Neue) often come up from slide decks that were originally created in Keynote.

If there's a Windows/Powerpoint genius somewhere in the lab, maybe they can figure out where this comes from and how to fix it.   The presentation is usable as is, so I'm not going to waste any more time on it.

**Comment by abhutta0** [comment]
I can confirm that. I was able to find some of those in the new text that was added. Gave up on looking at each slide to track them down. "Find/Replace Font" didn't work for me too.

**Comment by mwand** [comment]
I saved and pushed with "don't embed fonts", and it went away for me.   Can you confirm?

**Comment by abhutta0** [comment]
I don't have that option. But I was able to save the file with the errors. When I open it again and try to save it, I still get errors for 2 fonts

**Comment by mwand** [comment]
Have you tried the version I pushed in main: 908038d

**Comment by abhutta0** [comment]
works. No errors. Thanks

**Pull request merged**
